### PR TITLE
Upgrade to serde 0.9

### PR DESCRIPTION
**Pull request by KodrAus**
Howdy! This is a reactionary upgrade to `serde 0.9`. I say reactionary because all I've done is the least amount of work I can to make it build and pass tests.

There is one major wrinkle and I'm not sure how to progress it; `serde_json::to_value()` now returns a `Result`, and we're kind of assuming in the `to_object` methods that nothing will fail. You can see I'm calling `expect()`, which is basically how `serde_json` used to work, but doesn't now.

As the `serde` API drifts further away from `rustc_serialize` I think it's going to get harder to maintain the compatibility layer. How do you think we should move forward?

I'm thinking we could:
- Keep the `expect` or similar and document when `to_object()` can panic
- Or update `to_object()` to return a `Result`, that's always `Ok` with `rustc_serialize`

CC: @frewsxcv

### CODE REVIEW

**Comment by frewsxcv** [comment]
I think it's clear Serde is the future of serialization in the Rust ecosystem. How do you feel about dropping support for rustc-serialize?

**Comment by KodrAus** [comment]
Personally I'm only using `serde` support so am totally on board with that. It would make the codebase simpler again. There could be some other users with different opinions though.

**Comment by frewsxcv** [comment]
I appreciate your initial effort to support both, but I think we're good to remove rustc-serialize support.

**Comment by frewsxcv** [comment]
Looks like you'll need to update the Travis config to stop testing 'with-serde'

**Comment by KodrAus** [comment]
Ah yes I'll update that :+1: I was going to do a bit of boyscouting too and clean up the `serde` uses and some docs.

**Pull request merged**
