### PR TITLE
Bump geo and num-traits crates.

### PR DESCRIPTION
**Pull request by frewsxcv**
* geo: 0.6 -> 0.7
* num-traits: 0.1 -> 0.2

### CODE REVIEW

**Comment by ingalls** [comment]
@frewsxcv would it be possible for you to cut a crates.io release for this?

**Comment by frewsxcv** [comment]
@ingalls done! https://github.com/georust/rust-geojson/pull/92

**Comment by ingalls** [comment]
Thanks a ton @frewsxcv

**Pull request merged**
